import { type SetPlan, type Track } from './types';

// Generate realistic waveform data
function generateWaveform(energy: number, bars: number = 64): number[] {
  const waveform: number[] = [];
  for (let i = 0; i < bars; i++) {
    const position = i / bars;
    // Create natural energy curve with intro/outro dips
    let base = energy * 0.6;
    if (position < 0.1) base *= position / 0.1; // Intro ramp
    if (position > 0.85) base *= (1 - position) / 0.15; // Outro fade
    // Add variation
    const variation = Math.sin(i * 0.5) * 1.5 + Math.random() * 2;
    waveform.push(Math.max(1, Math.min(10, base + variation)));
  }
  return waveform;
}

export const demoTracks: Track[] = [
  {
    id: 'hash-berlin-sunrise',
    title: 'Berlin Sunrise',
    artist: 'Linea',
    bpm: 126,
    key: '8A',
    energy: 6,
    status: 'analyzed',
    needsReview: false,
    path: '/music/Linea/Berlin Sunrise.wav',
    cues: [
      { beat: 0, label: 'Load', type: 'Load' },
      { beat: 64, label: 'Drop', type: 'Drop' },
      { beat: 384, label: 'Outro', type: 'OutroStart' },
    ],
    sections: [
      { start: 0, end: 64, label: 'Intro' },
      { start: 64, end: 320, label: 'Drop' },
      { start: 320, end: 384, label: 'Outro' },
    ],
    transitionWindows: [
      { start: 0, end: 32, label: 'intro_mix' },
      { start: 352, end: 384, label: 'outro_mix' },
    ],
    waveformSummary: generateWaveform(6),
  },
  {
    id: 'hash-midnight-arc',
    title: 'Midnight Arc',
    artist: 'Edda',
    bpm: 128,
    key: '9A',
    energy: 7,
    status: 'analyzed',
    needsReview: false,
    path: '/music/Edda/Midnight Arc.flac',
    cues: [
      { beat: 0, label: 'Load', type: 'Load' },
      { beat: 128, label: 'Break', type: 'Breakdown' },
      { beat: 192, label: 'Build', type: 'Build' },
      { beat: 256, label: 'Drop 2', type: 'Drop' },
    ],
    sections: [
      { start: 0, end: 64, label: 'Intro' },
      { start: 64, end: 160, label: 'Break' },
      { start: 160, end: 256, label: 'Build/Drop' },
      { start: 256, end: 320, label: 'Outro' },
    ],
    transitionWindows: [
      { start: 16, end: 48, label: 'intro_mix' },
      { start: 240, end: 272, label: 'outro_mix' },
    ],
    waveformSummary: generateWaveform(7),
  },
  {
    id: 'hash-neon-bridge',
    title: 'Neon Bridge',
    artist: 'MonoKite',
    bpm: 124,
    key: '7B',
    energy: 5,
    status: 'analyzed',
    needsReview: true,
    path: '/music/MonoKite/Neon Bridge.mp3',
    cues: [
      { beat: 0, label: 'Load', type: 'Load' },
      { beat: 48, label: 'First Downbeat', type: 'FirstDownbeat' },
      { beat: 320, label: 'Outro', type: 'OutroStart' },
    ],
    sections: [
      { start: 0, end: 48, label: 'Intro' },
      { start: 48, end: 288, label: 'Body' },
      { start: 288, end: 352, label: 'Outro' },
    ],
    transitionWindows: [
      { start: 0, end: 24, label: 'intro_mix' },
      { start: 304, end: 336, label: 'outro_mix' },
    ],
    waveformSummary: generateWaveform(5),
  },
  {
    id: 'hash-delta-peak',
    title: 'Delta Peak',
    artist: 'Ravel',
    bpm: 130,
    key: '10A',
    energy: 8,
    status: 'analyzed',
    needsReview: false,
    path: '/music/Ravel/Delta Peak.aiff',
    cues: [
      { beat: 0, label: 'Load', type: 'Load' },
      { beat: 64, label: 'Drop', type: 'Drop' },
      { beat: 256, label: 'Breakdown', type: 'Breakdown' },
      { beat: 320, label: 'Drop 2', type: 'Drop' },
    ],
    sections: [
      { start: 0, end: 64, label: 'Intro' },
      { start: 64, end: 256, label: 'Drop' },
      { start: 256, end: 320, label: 'Breakdown' },
      { start: 320, end: 400, label: 'Outro' },
    ],
    transitionWindows: [
      { start: 0, end: 32, label: 'intro_mix' },
      { start: 360, end: 400, label: 'outro_mix' },
    ],
    waveformSummary: generateWaveform(8),
  },
  {
    id: 'hash-cascade-flow',
    title: 'Cascade Flow',
    artist: 'Synthetic Dreams',
    bpm: 122,
    key: '6A',
    energy: 4,
    status: 'analyzed',
    needsReview: false,
    path: '/music/Synthetic Dreams/Cascade Flow.wav',
    cues: [
      { beat: 0, label: 'Load', type: 'Load' },
      { beat: 32, label: 'First Beat', type: 'FirstDownbeat' },
    ],
    sections: [
      { start: 0, end: 64, label: 'Intro' },
      { start: 64, end: 256, label: 'Body' },
      { start: 256, end: 320, label: 'Outro' },
    ],
    transitionWindows: [
      { start: 0, end: 48, label: 'intro_mix' },
      { start: 280, end: 320, label: 'outro_mix' },
    ],
    waveformSummary: generateWaveform(4),
  },
  {
    id: 'hash-pulse-drive',
    title: 'Pulse Drive',
    artist: 'Technocraft',
    bpm: 134,
    key: '11A',
    energy: 9,
    status: 'analyzed',
    needsReview: false,
    path: '/music/Technocraft/Pulse Drive.flac',
    cues: [
      { beat: 0, label: 'Load', type: 'Load' },
      { beat: 32, label: 'Kick In', type: 'FirstDownbeat' },
      { beat: 128, label: 'Drop', type: 'Drop' },
      { beat: 256, label: 'Build', type: 'Build' },
      { beat: 288, label: 'Peak', type: 'Drop' },
    ],
    sections: [
      { start: 0, end: 32, label: 'Intro' },
      { start: 32, end: 128, label: 'Build' },
      { start: 128, end: 256, label: 'Drop' },
      { start: 256, end: 320, label: 'Breakdown' },
      { start: 320, end: 384, label: 'Outro' },
    ],
    transitionWindows: [
      { start: 0, end: 24, label: 'intro_mix' },
      { start: 350, end: 384, label: 'outro_mix' },
    ],
    waveformSummary: generateWaveform(9),
  },
  {
    id: 'hash-ambient-drift',
    title: 'Ambient Drift',
    artist: 'Horizon',
    bpm: 118,
    key: '5B',
    energy: 3,
    status: 'analyzed',
    needsReview: false,
    path: '/music/Horizon/Ambient Drift.mp3',
    cues: [
      { beat: 0, label: 'Load', type: 'Load' },
      { beat: 64, label: 'Melody', type: 'FirstDownbeat' },
    ],
    sections: [
      { start: 0, end: 96, label: 'Intro' },
      { start: 96, end: 288, label: 'Body' },
      { start: 288, end: 384, label: 'Outro' },
    ],
    transitionWindows: [
      { start: 0, end: 64, label: 'intro_mix' },
      { start: 320, end: 384, label: 'outro_mix' },
    ],
    waveformSummary: generateWaveform(3),
  },
  {
    id: 'hash-chrome-echo',
    title: 'Chrome Echo',
    artist: 'Digital Mind',
    bpm: 128,
    key: '8A',
    energy: 7,
    status: 'analyzed',
    needsReview: true,
    path: '/music/Digital Mind/Chrome Echo.wav',
    cues: [
      { beat: 0, label: 'Load', type: 'Load' },
      { beat: 64, label: 'Drop', type: 'Drop' },
      { beat: 192, label: 'Break', type: 'Breakdown' },
      { beat: 256, label: 'Peak', type: 'Drop' },
    ],
    sections: [
      { start: 0, end: 64, label: 'Intro' },
      { start: 64, end: 192, label: 'Drop' },
      { start: 192, end: 256, label: 'Break' },
      { start: 256, end: 352, label: 'Outro' },
    ],
    transitionWindows: [
      { start: 16, end: 48, label: 'intro_mix' },
      { start: 300, end: 352, label: 'outro_mix' },
    ],
    waveformSummary: generateWaveform(7),
  },
  {
    id: 'hash-solar-wind',
    title: 'Solar Wind',
    artist: 'Cosmos',
    bpm: 126,
    key: '9B',
    energy: 6,
    status: 'analyzed',
    needsReview: false,
    path: '/music/Cosmos/Solar Wind.flac',
    cues: [
      { beat: 0, label: 'Load', type: 'Load' },
      { beat: 48, label: 'Synth', type: 'FirstDownbeat' },
      { beat: 128, label: 'Build', type: 'Build' },
      { beat: 160, label: 'Drop', type: 'Drop' },
    ],
    sections: [
      { start: 0, end: 48, label: 'Intro' },
      { start: 48, end: 160, label: 'Build' },
      { start: 160, end: 288, label: 'Drop' },
      { start: 288, end: 352, label: 'Outro' },
    ],
    transitionWindows: [
      { start: 0, end: 32, label: 'intro_mix' },
      { start: 310, end: 352, label: 'outro_mix' },
    ],
    waveformSummary: generateWaveform(6),
  },
  {
    id: 'hash-quantum-state',
    title: 'Quantum State',
    artist: 'Particle',
    bpm: 132,
    key: '10B',
    energy: 8,
    status: 'pending',
    needsReview: false,
    path: '/music/Particle/Quantum State.aiff',
    cues: [],
    sections: [{ start: 0, end: 64, label: 'Intro' }],
    transitionWindows: [],
    waveformSummary: generateWaveform(8),
  },
  {
    id: 'hash-deep-current',
    title: 'Deep Current',
    artist: 'Submerge',
    bpm: 120,
    key: '4A',
    energy: 5,
    status: 'analyzed',
    needsReview: false,
    path: '/music/Submerge/Deep Current.mp3',
    cues: [
      { beat: 0, label: 'Load', type: 'Load' },
      { beat: 64, label: 'Bass', type: 'FirstDownbeat' },
      { beat: 256, label: 'Outro', type: 'OutroStart' },
    ],
    sections: [
      { start: 0, end: 64, label: 'Intro' },
      { start: 64, end: 256, label: 'Body' },
      { start: 256, end: 320, label: 'Outro' },
    ],
    transitionWindows: [
      { start: 0, end: 48, label: 'intro_mix' },
      { start: 280, end: 320, label: 'outro_mix' },
    ],
    waveformSummary: generateWaveform(5),
  },
  {
    id: 'hash-neon-rush',
    title: 'Neon Rush',
    artist: 'Velocity',
    bpm: 140,
    key: '12A',
    energy: 9,
    status: 'analyzed',
    needsReview: false,
    path: '/music/Velocity/Neon Rush.wav',
    cues: [
      { beat: 0, label: 'Load', type: 'Load' },
      { beat: 16, label: 'Kick', type: 'FirstDownbeat' },
      { beat: 64, label: 'Drop', type: 'Drop' },
      { beat: 192, label: 'Build', type: 'Build' },
      { beat: 224, label: 'Peak', type: 'Drop' },
    ],
    sections: [
      { start: 0, end: 64, label: 'Intro' },
      { start: 64, end: 192, label: 'Drop' },
      { start: 192, end: 256, label: 'Build' },
      { start: 256, end: 320, label: 'Outro' },
    ],
    transitionWindows: [
      { start: 0, end: 16, label: 'intro_mix' },
      { start: 280, end: 320, label: 'outro_mix' },
    ],
    waveformSummary: generateWaveform(9),
  },
  {
    id: 'hash-twilight-zone',
    title: 'Twilight Zone',
    artist: 'Dusk',
    bpm: 124,
    key: '7A',
    energy: 6,
    status: 'analyzed',
    needsReview: false,
    path: '/music/Dusk/Twilight Zone.flac',
    cues: [
      { beat: 0, label: 'Load', type: 'Load' },
      { beat: 32, label: 'Pad', type: 'FirstDownbeat' },
      { beat: 96, label: 'Drop', type: 'Drop' },
    ],
    sections: [
      { start: 0, end: 96, label: 'Intro' },
      { start: 96, end: 256, label: 'Drop' },
      { start: 256, end: 320, label: 'Outro' },
    ],
    transitionWindows: [
      { start: 0, end: 64, label: 'intro_mix' },
      { start: 280, end: 320, label: 'outro_mix' },
    ],
    waveformSummary: generateWaveform(6),
  },
  {
    id: 'hash-acid-rain',
    title: 'Acid Rain',
    artist: 'TB-303',
    bpm: 135,
    key: '3A',
    energy: 8,
    status: 'analyzed',
    needsReview: true,
    path: '/music/TB-303/Acid Rain.wav',
    cues: [
      { beat: 0, label: 'Load', type: 'Load' },
      { beat: 32, label: '303', type: 'FirstDownbeat' },
      { beat: 128, label: 'Filter', type: 'Build' },
      { beat: 192, label: 'Peak', type: 'Drop' },
    ],
    sections: [
      { start: 0, end: 64, label: 'Intro' },
      { start: 64, end: 192, label: 'Build' },
      { start: 192, end: 288, label: 'Drop' },
      { start: 288, end: 352, label: 'Outro' },
    ],
    transitionWindows: [
      { start: 0, end: 32, label: 'intro_mix' },
      { start: 310, end: 352, label: 'outro_mix' },
    ],
    waveformSummary: generateWaveform(8),
  },
  {
    id: 'hash-stellar-drift',
    title: 'Stellar Drift',
    artist: 'Nebula',
    bpm: 116,
    key: '2B',
    energy: 3,
    status: 'pending',
    needsReview: false,
    path: '/music/Nebula/Stellar Drift.mp3',
    cues: [],
    sections: [{ start: 0, end: 64, label: 'Intro' }],
    transitionWindows: [],
    waveformSummary: generateWaveform(3),
  },
  {
    id: 'hash-machine-heart',
    title: 'Machine Heart',
    artist: 'Circuit',
    bpm: 128,
    key: '8B',
    energy: 7,
    status: 'analyzed',
    needsReview: false,
    path: '/music/Circuit/Machine Heart.flac',
    cues: [
      { beat: 0, label: 'Load', type: 'Load' },
      { beat: 64, label: 'Main', type: 'Drop' },
      { beat: 192, label: 'Break', type: 'Breakdown' },
      { beat: 256, label: 'Return', type: 'Drop' },
    ],
    sections: [
      { start: 0, end: 64, label: 'Intro' },
      { start: 64, end: 192, label: 'Drop' },
      { start: 192, end: 256, label: 'Break' },
      { start: 256, end: 320, label: 'Outro' },
    ],
    transitionWindows: [
      { start: 0, end: 32, label: 'intro_mix' },
      { start: 288, end: 320, label: 'outro_mix' },
    ],
    waveformSummary: generateWaveform(7),
  },
];

export const demoSetPlan: SetPlan = {
  mode: 'Peak-time',
  order: [
    'hash-ambient-drift',
    'hash-cascade-flow',
    'hash-neon-bridge',
    'hash-twilight-zone',
    'hash-berlin-sunrise',
    'hash-chrome-echo',
    'hash-midnight-arc',
    'hash-delta-peak',
    'hash-pulse-drive',
    'hash-neon-rush',
  ],
  edges: [
    {
      from: 'hash-ambient-drift',
      to: 'hash-cascade-flow',
      score: 7.5,
      tempoDelta: 4,
      energyDelta: 1,
      keyRelation: '+1 Camelot',
      window: 'outro_mix → intro_mix',
      reason: 'Gentle opener: +4 BPM lift, +1 energy, harmonic +1 step',
    },
    {
      from: 'hash-cascade-flow',
      to: 'hash-neon-bridge',
      score: 7.8,
      tempoDelta: 2,
      energyDelta: 1,
      keyRelation: '+1 Camelot',
      window: 'outro_mix → intro_mix',
      reason: 'Smooth progression: +2 BPM, +1 energy, compatible keys',
    },
    {
      from: 'hash-neon-bridge',
      to: 'hash-twilight-zone',
      score: 8.2,
      tempoDelta: 0,
      energyDelta: 1,
      keyRelation: 'Same key family',
      window: 'outro_mix → intro_mix',
      reason: 'Perfect tempo match, +1 energy, harmonic blend',
    },
    {
      from: 'hash-twilight-zone',
      to: 'hash-berlin-sunrise',
      score: 7.9,
      tempoDelta: 2,
      energyDelta: 0,
      keyRelation: '+1 Camelot',
      window: 'outro_mix → intro_mix',
      reason: 'Maintain energy, +2 BPM groove shift',
    },
    {
      from: 'hash-berlin-sunrise',
      to: 'hash-chrome-echo',
      score: 8.5,
      tempoDelta: 2,
      energyDelta: 1,
      keyRelation: 'Same key',
      window: 'outro_mix → intro_mix',
      reason: 'Same key 8A, +2 BPM, building energy',
    },
    {
      from: 'hash-chrome-echo',
      to: 'hash-midnight-arc',
      score: 8.1,
      tempoDelta: 0,
      energyDelta: 0,
      keyRelation: '+1 Camelot',
      window: 'outro_mix → intro_mix',
      reason: 'Perfect tempo hold at 128, harmonic lift to 9A',
    },
    {
      from: 'hash-midnight-arc',
      to: 'hash-delta-peak',
      score: 8.4,
      tempoDelta: 2,
      energyDelta: 1,
      keyRelation: '+1 Camelot',
      window: 'outro_mix → intro_mix',
      reason: 'Climbing to peak: +2 BPM, +1 energy, 9A→10A harmonic',
    },
    {
      from: 'hash-delta-peak',
      to: 'hash-pulse-drive',
      score: 8.7,
      tempoDelta: 4,
      energyDelta: 1,
      keyRelation: '+1 Camelot',
      window: 'outro_mix → intro_mix',
      reason: 'Peak energy push: +4 BPM to 134, max energy incoming',
    },
    {
      from: 'hash-pulse-drive',
      to: 'hash-neon-rush',
      score: 9.1,
      tempoDelta: 6,
      energyDelta: 0,
      keyRelation: '+1 Camelot',
      window: 'outro_mix → intro_mix',
      reason: 'Full send: +6 BPM to 140, hold max energy, 11A→12A climax',
    },
  ],
};
