import { type SetPlan, type Track } from './types';

export const demoTracks: Track[] = [
  {
    id: 'hash-berlin-sunrise',
    title: 'Berlin Sunrise',
    artist: 'Linea',
    bpm: 126,
    key: '8A',
    energy: 6,
    status: 'analyzed',
    needsReview: false,
    path: '/music/Linea/Berlin Sunrise.wav',
    cues: [
      { beat: 0, label: 'Load', type: 'Load' },
      { beat: 64, label: 'Drop', type: 'Drop' },
      { beat: 384, label: 'Outro', type: 'OutroStart' },
    ],
    sections: [
      { start: 0, end: 64, label: 'Intro' },
      { start: 64, end: 320, label: 'Drop' },
      { start: 320, end: 384, label: 'Outro' },
    ],
    transitionWindows: [
      { start: 0, end: 32, label: 'intro_mix' },
      { start: 352, end: 384, label: 'outro_mix' },
    ],
    waveformSummary: [4, 6, 5, 7, 8, 7, 6, 5, 4, 6, 7, 6, 5],
  },
  {
    id: 'hash-midnight-arc',
    title: 'Midnight Arc',
    artist: 'Edda',
    bpm: 128,
    key: '9A',
    energy: 7,
    status: 'analyzed',
    needsReview: false,
    path: '/music/Edda/Midnight Arc.flac',
    cues: [
      { beat: 0, label: 'Load', type: 'Load' },
      { beat: 128, label: 'Break', type: 'Breakdown' },
      { beat: 192, label: 'Build', type: 'Build' },
      { beat: 256, label: 'Drop 2', type: 'Drop' },
    ],
    sections: [
      { start: 0, end: 64, label: 'Intro' },
      { start: 64, end: 160, label: 'Break' },
      { start: 160, end: 256, label: 'Build/Drop' },
      { start: 256, end: 320, label: 'Outro' },
    ],
    transitionWindows: [
      { start: 16, end: 48, label: 'intro_mix' },
      { start: 240, end: 272, label: 'outro_mix' },
    ],
    waveformSummary: [3, 4, 5, 7, 8, 9, 9, 8, 7, 6, 6, 5, 5],
  },
  {
    id: 'hash-neon-bridge',
    title: 'Neon Bridge',
    artist: 'MonoKite',
    bpm: 124,
    key: '7B',
    energy: 5,
    status: 'analyzed',
    needsReview: true,
    path: '/music/MonoKite/Neon Bridge.mp3',
    cues: [
      { beat: 0, label: 'Load', type: 'Load' },
      { beat: 48, label: 'First Downbeat', type: 'FirstDownbeat' },
      { beat: 320, label: 'Outro', type: 'OutroStart' },
    ],
    sections: [
      { start: 0, end: 48, label: 'Intro' },
      { start: 48, end: 288, label: 'Body' },
      { start: 288, end: 352, label: 'Outro' },
    ],
    transitionWindows: [
      { start: 0, end: 24, label: 'intro_mix' },
      { start: 304, end: 336, label: 'outro_mix' },
    ],
    waveformSummary: [2, 3, 3, 4, 5, 5, 6, 5, 4, 4, 5, 5, 6],
  },
  {
    id: 'hash-delta-peak',
    title: 'Delta Peak',
    artist: 'Ravel',
    bpm: 130,
    key: '10A',
    energy: 8,
    status: 'pending',
    needsReview: false,
    path: '/music/Ravel/Delta Peak.aiff',
    cues: [],
    sections: [{ start: 0, end: 64, label: 'Intro' }],
    transitionWindows: [],
    waveformSummary: [5, 6, 7, 8, 8, 9, 9, 8, 7, 7, 6, 6, 5],
  },
];

export const demoSetPlan: SetPlan = {
  mode: 'Warm-up',
  order: ['hash-neon-bridge', 'hash-berlin-sunrise', 'hash-midnight-arc'],
  edges: [
    {
      from: 'hash-neon-bridge',
      to: 'hash-berlin-sunrise',
      score: 7.2,
      tempoDelta: 2,
      energyDelta: 1,
      keyRelation: '+1 Camelot',
      window: 'intro_mix → outro_mix',
      reason: 'Tempo +2 BPM, +1 energy, +1 Camelot (smooth lift)',
    },
    {
      from: 'hash-berlin-sunrise',
      to: 'hash-midnight-arc',
      score: 8.1,
      tempoDelta: 2,
      energyDelta: 1,
      keyRelation: '+1 Camelot',
      window: 'intro_mix → outro_mix',
      reason: 'Harmonic +1, steady energy climb, outro→intro overlap',
    },
  ],
};
